version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/football  # Use the internal port 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api  # This is fine for frontend-backend communication
    networks:
      - my-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football  # Fixed the POSTGRES_DB value to match the name of the database
    ports:
      - "5434:5432"  # Expose the internal port 5432 as 5434 on the host machine
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
